#!/bin/bash/

echo "enter current amount:"
read cur_amt

dp=`expr $cur_amt \* 50 / 100`
da=`expr $cur_amt + $dp \* 35 / 100`
hra=`expr $cur_amt + $dp \* 8 / 100`
ma=`expr $cur_amt + $dp \* 3 / 100`
pf=`expr $cur_amt + $dp \* 10 / 100`
echo "the total salary is:"
salary=`expr $cur_amt + $dp + $da + $hra + $ma - $pf`
echo $salary
